SET IDENTITY_INSERT [dbo].[Users] ON
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1001, N'Alice', N'-1234556', N'alice@gmail.com', N'12345', N'89, Taman Red', N'Kedah', N'08000', N'Sungai Petani', 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1002, N'Tim', NULL, N'tim@hotmail.com', N'54321', N'80, Taman Hot', N'Kedah', N'08000', N'Sungai Petani', 0, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1003, N'Rick', NULL, N'rick@gmail.com', N'', NULL, NULL, NULL, NULL, 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1004, N'Aeron', NULL, N'aeron@gmail.com', N'', NULL, NULL, NULL, NULL, 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1005, N'Timmy', NULL, N'timmy@gmail.com', N'', NULL, NULL, NULL, NULL, 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1006, N'alice', NULL, N'alice@gmail.com', N'12345', N'89, Taman Red', N'Kedah', N'08000', N'Sungai Petani', 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1007, N'Tim', NULL, N'tim@hotmail.com', N'54321', N'80, Taman Hot', N'Kedah', N'08000', N'Sungai Petani', 0, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1009, N'', NULL, N'', N'', NULL, NULL, NULL, NULL, 1, <SQLVARIANT>, 0)
INSERT INTO [dbo].[Users] ([userID], [userName], [phoneNo], [email], [password], [address], [state], [postcode], [city], [accountStatus], [profileImage], [isArtist]) VALUES (1010, N'UserA', NULL, N'user@gmail.com', N'1234', NULL, NULL, NULL, NULL, 1, <SQLVARIANT>, 0)
SET IDENTITY_INSERT [dbo].[Users] OFF
